mysite/auth_test/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView

from auth_test import views
urlpatterns = patterns('', 
    url(r'^$', views.index, name = 'index'),
    url(r'^login_user/$', views.login_user, name = 'login_user'),
    url(r'^create_account/$', views.create_account, name = 'create_account'),
    url(r'^logout_user/$', views.logout_user, name = 'logout_user'),
    )

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from mysite import views

admin.autodiscover()

urlpatterns = patterns('',
	# url(r'^$', 'mysite.views.home', name='home'),

    # for Max's facebook login
    # url(r'^main/index.html', 'fb_login_test.views.login', name='login'),

    # url(r'^login_facebook/?', 'fb_login_test.views.login', name='login_facebook'),
    # url(r'^logged_in_facebook/?', 'fb_login_test.views.show_login_view', name = 'logged_in_facebook'),

    # url(r'^logout.html', 'fb_login_test.views.logout', name='logout'),
    # url(r'^logout/?', 'fb_login_test.views.logout', name='logout'),



    # url(r'^get_friends_name_uid/?', 'fb_login_test.views.get_friends_name_uid', name='get_friends_name_uid'),


    # For social_auth
    # url(r'', include('social_auth.urls')),
    # url(r'^login/$', redirect_to, {'url':'/login/facebook'}),

	url(r'^$', views.all_sites, name='all_sites'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^fb_login_test/', include('fb_login_test.urls', namespace="fb_login_test")),
    url(r'^auth_test/', include('auth_test.urls', namespace="auth_test")),
    url(r'^pull_movies_test/', include('pull_movies_test.urls', namespace="pull_movies_test")),
    # url(r'^facebook_app/', include('facebook_app.urls', namespace="facebook_app")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/polls/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from polls.models import Poll

from polls import views
urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
	url(r'^(?P<poll_id>\d+)/mobile/$', views.mobile_detail, name='mobile_detail'),

    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),

    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),

    # ex: /polls/javascript/
    url(r'^javascript/$', views.javascript_site, name='javascript'),
)

# urlpatterns = patterns('',
#     url(r'^$',
#         ListView.as_view(
#             queryset=Poll.objects.order_by('-pub_date')[:5],
#             context_object_name='latest_poll_list',
#             template_name='polls/index.html'),
#         name='index'),
#     url(r'^(?P<pk>\d+)/$',
#         DetailView.as_view(
#             model=Poll,
#             template_name='polls/detail.html'),
#         name='detail'),
#     url(r'^(?P<pk>\d+)/results/$',
#         DetailView.as_view(
#             model=Poll,
#             template_name='polls/results.html'),
#         name='results'),
#     url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote', name='vote'),
# )

mysite/auth_test/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, models, login, logout
from django.db import IntegrityError
from fb_login_test import views as fb_login_test_views

def index(request):
    if request.user.is_authenticated():
        return authenticated(request)
    else:
        return render(request, 'auth_test/index.html', {'message': ''})

def login_user(request):
    if request.user.is_authenticated():
        return authenticated(request)
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username = username, password = password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return authenticated(request)
        else:
            return failed_auth(request)
    else:
        return invalid_login(request)


def create_account(request):
    username = request.POST['username']
    password = request.POST['password']
    password_copy = request.POST['password_copy']
    if (password_copy != password):
        return render(request, 'auth_test/index.html', {'message': 'Password does not match.'})

    # Create a new user and render logged in page
    try:
        user = models.User.objects.create_user(username = username, password = password)
        user.save()
        user = authenticate(username = username, password = password)
        login(request, user)
    except IntegrityError:
        return render(request, 'auth_test/index.html', {'message': 'Username already taken.'})
    
    return authenticated(request)

def logout_user(request):
    logout(request)
    return index(request)

def failed_auth(request):
    return render(render, 'auth_test/failed_auth.html')

def invalid_login(request):
    return render(render, 'auth_test/invalid_login.html')

def authenticated(request):
    return fb_login_test_views.logging_in(request)

def not_authenticated(request):
    return render(request, 'auth_test/not_authenticated.html')

mysite/auth_test/templates/auth_test/authenticated.html
{% load url from future %}
<html>
<body>
    <h1>You are authenticated!</h1>
    <h2>You are logged in as {{ username }}</h2>
    <a href="{% url 'auth_test:logout_user' %}">Log out</a>

</body>
</html>

mysite/auth_test/templates/auth_test/failed_auth.html
<html>
<body>
    <h1>Failed authentication!</h1>
</body>
</html>

mysite/auth_test/templates/auth_test/fb_channel_file.html
 <script src="//connect.facebook.net/en_US/all.js"></script>

mysite/auth_test/templates/auth_test/index.html
{% load url from future %}
<html>
<body>

    <div id="fb-root"></div>
        <script>
          window.fbAsyncInit = function() {
          FB.init({
            appId      : '359702040796778', // App ID
            // channelUrl : '//WWW.YOUR_DOMAIN.COM/channel.html', // Channel File
            status     : true, // check login status
            cookie     : true, // enable cookies to allow the server to access the session
            xfbml      : true  // parse XFBML
          });

          // Here we subscribe to the auth.authResponseChange JavaScript event. This event is fired
          // for any auth related change, such as login, logout or session refresh. This means that
          // whenever someone who was previously logged out tries to log in again, the correct case below 
          // will be handled. 
          FB.Event.subscribe('auth.authResponseChange', function(response) {
            // Here we specify what we do with the response anytime this event occurs. 
            if (response.status === 'connected') {
              // The response object is returned with a status field that lets the app know the current
              // login status of the person. In this case, we're handling the situation where they 
              // have logged in to the app.
              testAPI();
            } else if (response.status === 'not_authorized') {
              // In this case, the person is logged into Facebook, but not into the app, so we call
              // FB.login() to prompt them to do so. 
              // In real-life usage, you wouldn't want to immediately prompt someone to login 
              // like this, for two reasons:
              // (1) JavaScript created popup windows are blocked by most browsers unless they 
              // result from direct user interaction (such as a mouse click)
              // (2) it is a bad experience to be continually prompted to login upon page load.
              FB.login();
            } else {
              // In this case, the person is not logged into Facebook, so we call the login() 
              // function to prompt them to do so. Note that at this stage there is no indication
              // of whether they are logged into the app. If they aren't then they'll see the Login
              // dialog right after they log in to Facebook. 
              // The same caveats as above apply to the FB.login() call here.
              FB.login();
            }
          });
          };

          // Load the SDK asynchronously
          (function(d){
           var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
           if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/en_US/all.js";
           ref.parentNode.insertBefore(js, ref);
          }(document));

          // Here we run a very simple test of the Graph API after login is successful. 
          // This testAPI() function is only called in those cases. 
          function testAPI() {
            console.log('Welcome!  Fetching your information.... ');
            FB.api('/me', function(response) {
              console.log('Good to see you, ' + response.name + '.');
            });
            FB.api('/me/friends', function (response) {
                console.log("Here's all your friends: ") ;
                for (var i = response.data.length - 1; i >= 0; i--) {
                    console.log(response.data[i].name);
                    console.log(response.data[i].id);
                };
            });
          }
        </script>
<!--Below we include the Login Button social plugin. This button uses the JavaScript SDK to-->
<!--present a graphical Login button that triggers the FB.login() function when clicked.-->
    <fb:login-button show-faces="true" width="200" max-rows="1"></fb:login-button>


    <ur id = "friend_list"> 
        


    </ur>

    <h1>Welcome to auth test index page!</h1>
    <h2>Please login:</h2>
    <form action = "{% url 'auth_test:login_user' %}" method = "post"> 
        {% csrf_token %}
        username: <input type = "text" name = "username"><br>
        password: <input type = "text" name = "password"><br>
        <input type = "submit" value = "log in" >
    </form>

    <br>
    <h2>Register a new account:</h2>
    <form action = "{% url 'auth_test:create_account' %}" method = "post"> 
        {% csrf_token %}
        username: <input type = "text" name = "username"><br>
        password: <input type = "text" name = "password"><br>
        retype password: <input type = "text" name = "password_copy"><br>
        <input type = "submit" value = "Create new account" >
    </form>
    <h2>{{ message }}</h2>


    <div id = "div1"></div>

    <script type="text/javascript">
        document.write("<p>This is a javascript paragraph</p>");
        document.getElementById("div1").innerHTML="This is content in div 1";

    </script>


<!--     <div id="fb-root"></div>
    <script src="http://connect.facebook.net/en_US/all.js#
    appId=YOUR_APP_ID&amp;xfbml=1">
    </script>

    <fb:login-button show-faces="true" width="200" max-rows="1" 
    perms="user_likes, friends_likes"></fb:login-button> -->

</body>
</html>

mysite/auth_test/templates/auth_test/invalid_login.html
<html>
<body>
    <h1>Invalid login!</h1>
    <a href="/auth_test/">Retry</a>
</body>
</html>

mysite/auth_test/templates/auth_test/not_authenticated.html
<html>
<body>
    <h1>You are NOT authenticated!</h1>
</body>
</html>